### ISSUE TITLE
Use GitHub action to rebuild service files. 

### ISSUE THREAD

**Issue by adam-fowler** [soto-project/soto#207]
We should keep the service files more up to date with changes in aws-sdk-go model files. 

**Describe the solution you'd like**
I’d like to create a github action that is run once a week that would run the update models script, test the results and if successful commit the changes.

**Comment by fabianfett** [comment]
@adam-fowler I can do that, if you want me to. Just one question where do we load the json model files? Do we have a included bash script for this?

**Comment by adam-fowler** [comment]
> @adam-fowler I can do that, if you want me to. Just one question where do we load the json model files? Do we have a included bash script for this?

https://github.com/swift-aws/aws-sdk-swift/blob/master/scripts/update_models.sh

**Comment by adam-fowler** [comment]
@fabianfett You had a chance to look at this yet.

**Comment by fabianfett** [comment]
@adam-fowler sorry no i haven’t yet.

**Comment by adam-fowler** [comment]
@fabianfett no worries

**Comment by adam-fowler** [comment]
#392
