### ISSUE TITLE
`lambda.listFunctions` `masterRegion` should be a `SotoCore.Region`

### ISSUE THREAD

**Issue by helje5** [soto-project/soto#382]
The `masterRegion` parameter is currently a `String?`, but should probably be a `SotoCore.Region` struct.

**Comment by adam-fowler** [comment]
Ideally yes. The swift service files are auto-generated from json model files and these json model files don't have a Region type. Each services has their own setup for regions, if they need it. This is how master region is defined for Lambda
```
    "MasterRegion":{
      "type":"string",
      "pattern":"ALL|[a-z]{2}(-gov)?-[a-z]+-\\d{1}"
    },
```

**Comment by adam-fowler** [comment]
You might be lucky after all #384
