### ISSUE TITLE
The contentMd5 field in a S3.PutObjectRequest is not working

### ISSUE THREAD

**Issue by rnikander** [soto-project/soto#389]
**Describe the bug**

If I upload a simple file to S3, and I give it the wrong MD5, the file uploads without error. In contrast, I tested the Java SDK and it behaves as expected – passing the wrong MD5 throws an error and the file is not uploaded.

**To Reproduce**

Run this sample code:

    import CryptoKit
    extension Data {
        /// Convenience for S3 uploads
        func base64MD5() -> String {
            let md5 = Insecure.MD5.hash(data: self)
            return Data(md5).base64EncodedString()
        }
    }
    func testChecksumSmallFile() throws {
        let bucket = "your-bucket-name-here"
        let s3 = S3()
        let contentText = "hello world 123"
        let bodyData = contentText.data(using: .utf8)!
        let wrongData = (contentText + "x").data(using: .utf8)!
        let md5 = bodyData.base64MD5()
        let wrongMD5 = wrongData.base64MD5()
        print("      md5 : \(md5)")
        print("wrong md5 : \(wrongMD5)")
        let putObjectRequest = S3.PutObjectRequest(body: bodyData, bucket: bucket,
                                                   contentLength: Int64(bodyData.count),
                                                   contentMD5: wrongMD5,
                                                   contentType: "text/plain",
                                                   key: "folder1/hello.txt")
        let fut = s3.putObject(putObjectRequest)
        fut.whenSuccess { resp in
            print("success \(resp)")
        }
        fut.whenFailure { e in
            print("failure \(e)")            
        }
        try fut.wait()
    }

**Expected behavior**
There should be some kind of error from S3 and the file should not upload.

**Setup (please complete the following information):**
 - OS: macOS Big Sur 11.0 Beta
 - Version of aws-sdk-swift: 4.9.0
 - Authentication mechanism: .aws/credentials file

**Comment by adam-fowler** [comment]
The S3 module calculates the `contentMD5` for you. So whatever value you provider will be overidden. See https://github.com/soto-project/soto/blob/3ccbab5724df1cc2592f1b83420ff010ce986e86/Sources/Soto/Extensions/S3/S3RequestMiddleware.swift#L99

**Comment by adam-fowler** [comment]
I could have it not produce an MD5 if you have already provided one

**Comment by rnikander** [comment]
I think that's better.  In my case I have a lot of big files to upload, and I already have the MD5, so it's nice to not have to recalculate it. 

I wonder if it would be even better to mirror the Rest API and allow not producing it at all. I don't need that at the moment, but I'm guessing there are situations where people don't care and don't want to spend CPU calculating it.

I noticed the same issue with `UploadPartRequest` for multipart uploads.

**Comment by adam-fowler** [comment]
#396
