### ISSUE TITLE
Compile time issues

### ISSUE THREAD

**Issue by rohitst** [soto-project/soto#403]
**Describe the bug**
On my (granted old) system my app normally takes about 20 seconds to compile and deploy to the emulator, but with just AWSSDKCORE and S3 it takes 15 mins+. 

**To Reproduce**
1. Add github source via xcode 'Swift Frameworks'. Choose only AWSSDKCORE and S3.
2. Add these to the target
3. Compile

**Expected behavior**
Ideally only these module would need compilation once. It seems that build is compiling all of the modules in soto

**Setup (please complete the following information):**
 - iOS Swift 5 only project compiling on Mac OSX 10.5.5
 - Version 4.0

**Comment by adam-fowler** [comment]
Did you choose the module AWSSDKSwift? If so remove it. You don't need it.

**Comment by adam-fowler** [comment]
@rohitst did removing the dependency on AWSSDKSwift fix your issue?

**Comment by rohitst** [comment]
@adam-fowler Yes I can confirm that it still compiles and runs without AWSSDKSwift on the target. Compile time went to to 2 mins.


Thank you, apologies I'm a new to iOS dev coming from the android world.

**Comment by adam-fowler** [comment]
@rohitst no worries, the fact we have an AWSSDKSwift target that includes every other target is a little stupid. V5.0 of Soto will remove that target. Nobody needs to compile 200 libraries.
