### ISSUE TITLE
Distinguish different types of errors from AWS in response handlers

### ISSUE THREAD

**Issue by alexfedoseev** [soto-project/soto#406]
**Is your feature request related to a problem? Please describe.**
When I use `.whenComplete` I see opaque `Error` type in the `.failure` case. I can print it but I can't react properly in the app. I'm not sure if it's possible to look into the error to figure out the reason of failure.

**Describe the solution you'd like**
I'd like to distinguish different types of errors from AWS to give meaningful suggestions to users in UI.

**Comment by adam-fowler** [comment]
Soto returns a number of different error types:
There is [AWSClientError](https://github.com/soto-project/soto-core/blob/45d9208543f3441c52bd379757d01207af56acda/Sources/AWSSDKSwiftCore/Error.swift#L135) for general client error returned by all services.
There is [AWSServerError](https://github.com/soto-project/soto-core/blob/45d9208543f3441c52bd379757d01207af56acda/Sources/AWSSDKSwiftCore/Error.swift#L54) for general server errors returned by all services
Each service has it's own Error type, for instance this is the S3 errors are [here](https://github.com/soto-project/soto/blob/main/Sources/Soto/Services/S3/S3_Error.swift)
If the error code returned by AWS is unrecognised then we return a [AWSResponseError](https://github.com/soto-project/soto-core/blob/45d9208543f3441c52bd379757d01207af56acda/Sources/AWSSDKSwiftCore/Error.swift#L22)

Here is an example of catching errors
```
do {
    let response = s3.putObject(.init(body: myData, bucket: "myBucket", key: "myKey").wait()
} catch S3ErrorType.noSuchBucket {
    deal with bucket not existing
} catch AWSClientError.authFailure(let message) {
    print(message)
    deal with invalid authorization credentials
}
```

**Comment by adam-fowler** [comment]
Hi @alexfedoseev has that given you enough info?

**Comment by alexfedoseev** [comment]
Hi @adam-fowler, yeah, more than enough, thank you! I almost finished error handling part and it worked great. The only issue I noticed is that even if I provide bad credentials, still `AWSClientError.authFailure` doesn't get matched. Let me know if it's an actual bug that deserves own issue. Other than that, all good 🙌

**Comment by adam-fowler** [comment]
> The only issue I noticed is that even if I provide bad credentials, still `AWSClientError.authFailure` doesn't get matched. Let me know if it's an actual bug that deserves own issue. Other than that, all good 🙌

That might be related to the service. Which service are you using?

As an aside the error objects will be changing with Soto V5. They might be slightly more awkward to use but will contain more info. I will make sure I document these changes so you hopefully don't need to post another issue :-)

**Comment by alexfedoseev** [comment]
> That might be related to the service. Which service are you using?

S3

**Comment by adam-fowler** [comment]
I had a look at this and yes S3 returns it own error for invalid credentials "InvalidAccessKeyId". To top this off they don't include this error in the interface model for the service. So all I can return is a generic AWSResponseError which includes the error code as a `String`. S3 is a law onto itself and have a load of special cases.
