### ISSUE TITLE
macOS : S3Tests fails on testPutGetObjectWithSpecialName 

### ISSUE THREAD

**Issue by sebsto** [soto-project/soto#415]
**Describe the bug**

S3Tests `testPutGetObjectWithSpecialName` fails on macOS with the below error message:

```
/Users/stormacq/Documents/code/swift/soto/Tests/SotoTests/Services/S3/S3Tests.swift:168: error: -[SotoTests.S3Tests testPutGetObjectWithSpecialName] : XCTAssertNoThrow failed: threw error "The request url is invalid format.
This error is internal. So please make a issue on https://github.com/soto-project/soto/issues to solve it."
```

**To Reproduce**
1. On MacOS : `git pull`
2. `swift test`

**Expected behavior**
Test suite should pass

**Setup (please complete the following information):**
 - OS: macOS 10.15.7
 - Version of aws-sdk-swift  latest on main branch 
 - Authentication mechanism : default (AWS credentials in ~/.aws/credentials ?)

**Additional context**

**Comment by adam-fowler** [comment]
@sebsto can you make sure you have latest `soto-core`. I added that test to specifically test some changes in `soto-core`. Prior to those changes it failed, but should now be fixed

**Comment by adam-fowler** [comment]
Looks like a Localstack issue. I've replicated it locally.

**Comment by sebsto** [comment]
> can you make sure you have latest soto-core

I do 

> I've replicated it locally.

Great.

**Comment by adam-fowler** [comment]
This is a issue with Localstack not listing files with "<" or ">" in the key correctly so I'm going to close.
