### ISSUE TITLE
A way to track S3 download/upload, for UI progress bars

### ISSUE THREAD

**Issue by rnikander** [soto-project/soto#423]
I'm writing a macOS app that uploads files to S3. It seems like with the `putObject` operation there is no way to watch the byte-by-byte progress. On a slow internet connection, an upload can take some time (10-20+ seconds), even when the file is too small for a multipart upload. 

I'd like a way to pass a callback into the `putObject` function, maybe part of the struct `S3.PutObjectRequest`. That callback would get called frequently, with info about how many bytes have been uploaded. This would allow me to implement a progress indicator in the user interface.

I'm focused on `putObject`, but obviously other operations could have a similar thing.

**Comment by adam-fowler** [comment]
If you are using v4.9 or earlier then no. There is no way to do this.

If you are using the v5.0 beta then you can use the streaming request payloads to do this. See [here](https://github.com/soto-project/soto/blob/5.x.x-docs/documentation/Streaming%20Payloads.md) for details on how it works. The `.fileHandle` payload mentioned in this article also takes a callback closure which is updated with how much of the file has been uploaded. As an aside if you want to cancel an upload you can throw an error from this callback.

Also if you are uploading files larger than 5mb then you can use the [multipart upload](https://github.com/soto-project/soto/blob/5.x.x-docs/documentation/S3%20Multipart%20Upload.md) which also provides progress callbacks.

**Comment by adam-fowler** [comment]
Hi @rnikander do you need any more info? Are you able to move to the v5 beta to take advantage of the streaming functionality?

**Comment by rnikander** [comment]
Yes, I can use the v5.0. I haven't had a chance to try it out yet, but I'm sure it work. Thank you for the response!

**Comment by rnikander** [comment]
I don't know how to use 5.0 beta. [This page suggests](https://github.com/soto-project/soto/blob/5.x.x-docs/README.md) I could use the same URL and put 5.0.0 for the version, but if I try that in Xcode I get an error "Failed to resolve dependencies ... because no versions of soto match the requirement 5.0.0..<6.0.0 and root depends on soto 5.0.0..<6.0.0, version solving failed."

**Comment by rnikander** [comment]
Ah nevermind, I got it. Xcode has a field for "branch". I used "5.x.x" there.
