### ISSUE TITLE
Streaming S3 putObject fails with timeout 

### ISSUE THREAD

**Issue by rnikander** [soto-project/soto#431]
I'm trying the 5.0.0 beta branch so I can upload files to S3 and monitor progress. I'm using the `AWSPayload.stream` and it works well, unless my file takes more than 20 seconds to upload. In that case the `putObject` future fails with `HTTPClientError.readTimeout`. 

I see the 20 seconds is used as default timeout: https://github.com/soto-project/soto-core/blob/0cbfc017125b4763c93128d2486789cf3cd0bde2/Sources/SotoCore/AWSServiceConfig.swift#L98

By code looks like this. The closure gets called about once per second to compute a new chuck to upload. But once 20 seconds elapse after the call to `putObject(req)`, it fails. I could of course increase the timeout, but I'm wondering if this is a bug.  It doesn't seem like the timeout should come into play here. It's not like S3 has stopped responding.

    let payload = AWSPayload.stream(size: blobSize) { eventLoop in 
         let chuck = ...
         return eventLoop.makeSucceededFuture(.byteBuffer(chunk))
    }
    let req = S3.PutObjectRequest(body: payload, bucket: bucket, key: key)
    let s3 = S3(client: awsClient, region: .useast1)
    let fut = s3.putObject(req)

**Comment by adam-fowler** [comment]
Hi, the timeout implementation comes from the implementation of the underlying HTTP client. It works based on deadlines, so `timeout` are timeouts for the whole operations and not just the connection. 

There are a number of different ways you can edit the timeout. First you can create your `S3` service object with a new timeout. 
```
let s3 = S3(client: awsClient, region: .useast1, timeout: .minutes(2))
```
You can create a new client from an existing one
```
let fut = s3.with(timeout: .minutes(2)).putObject(req)
```
If you have a long timeout for an upload operation but want it to return quicker for a connection timeout then you can provide your own HTTPClient, with edited connect timeout, when constructing the AWSClient.
```
import AsyncHTTPClient
let httpClient = HTTPClient(eventLoopGroupProvider: .createNew, configuration: .init(timeout: .init(connect: .seconds(10))))
let awsClient = AWSClient(httpClientProvider: .shared(httpClient))
```
In actual fact, I'm going to default the HTTPClient created by AWSClient to have a connect timeout, as they don't at the moment. I'll add some docs detailing the above.

**Comment by rnikander** [comment]
Ah, okay. That works for me. Thanks.

**Comment by 0xpablo** [comment]
Sorry to resurrect an old issue. It looks like Soto is passing a 20s timeout to the AWSServiceConfig. This timeout is indeed a deadline: 
```
        self.timeout = timeout ?? .seconds(20)
```

I'm wondering whether it should override that for the S3 client with a more reasonable default (the underlying HTTPClient should have reasonable defaults for things like the connection timeout).

If I should create a new issue to discuss this LMK.

Thanks!
