### ISSUE TITLE
Assertion failed error with larger file s3 putObject

### ISSUE THREAD

**Issue by rnikander** [soto-project/soto#433]
This code crashes. (Using `main` branch.)

    func testS3ErrorBigFile() {
        let cpf: CredentialProviderFactory = .static(accessKeyId: "..."
                                                     secretAccessKey: "...")
        let awsClient = AWSClient(credentialProvider: cpf, httpClientProvider: .createNew)
        let s3 = S3(client: awsClient, region: .useast1)

        let data = Data(count: 17_000_000)
        let bb = ByteBuffer(data: data)
        let chunkSize = 100_000
        var idx = 0
        let payload = AWSPayload.stream(size: bb.readableBytes) { eventLoop in 
            print("Sending chunk at \(idx)")
            let nRemaining = bb.readableBytes - idx
            let len = min(nRemaining, chunkSize)
            let chunk = bb.viewBytes(at: idx, length: len)!
            idx += chunkSize
            return eventLoop.makeSucceededFuture(.byteBuffer(ByteBuffer(chunk)))
        }
        let req = S3.PutObjectRequest(body: payload, bucket: "...", key: "...")
        let fut = s3.putObject(req)
        do {
            try fut.wait()
        } catch {
            print("Unexpected error \(error.localizedDescription)")
        }

        try! awsClient.syncShutdown()
    }

**Comment by rnikander** [comment]
Can't seem to get around this with a `s3.multipartUpload` either. This also crashes. Am I using it incorrectly?

    func testS3ErrorBigFileMultipart() {
        let cpf: CredentialProviderFactory = .static(accessKeyId: "...",
                                                     secretAccessKey: "...")
        let awsClient = AWSClient(credentialProvider: cpf, httpClientProvider: .createNew)
        let s3 = S3(client: awsClient, region: .useast1)

        let data = Data(count: 17_000_000)
        let entireBB = ByteBuffer(data: data)
        let chunkSize = 200_000
        let partSize = 5_000_000
        var partIdx = 0
        
        let req = S3.CreateMultipartUploadRequest(bucket: "...", key: "test-error")
        let fut = s3.multipartUpload(req) { eventLoop in
            let thisPartIdx = partIdx
            let partStart = partIdx * partSize
            let remaining = entireBB.readableBytes - partStart
            let partLen = min(remaining, partSize)
            let partBBView = entireBB.viewBytes(at: partStart, length: partLen)!
            let partBB = ByteBuffer(partBBView)
            var idx = 0 // within the part
            let payload = AWSPayload.stream(size: partBB.readableBytes) { eventLoop in
                let remainingInPart = partBB.readableBytes - idx
                let len = min(remainingInPart, chunkSize)
                let chunk = partBB.viewBytes(at: idx, length: len)!
                print("Returning chunk at \(idx), len=\(len) [part \(thisPartIdx)]")
                idx += chunkSize
                return eventLoop.makeSucceededFuture(.byteBuffer(ByteBuffer(chunk)))
            }
            print("Part idx \(partIdx), start=\(partStart), len=\(partLen)")
            partIdx += 1
            return eventLoop.makeSucceededFuture(payload)
        }
        
        do {
            try fut.wait()
        } catch {
            print("Unexpected error \(error.localizedDescription)")
        }

        try! awsClient.syncShutdown()
    }

Like the first example, the error is :
> Assertion failed: file NIO/ByteBuffer-core.swift, line 357
> 2020-11-09 15:53:50.371456-0500 CmdLineTool[74271:2496581] Assertion failed: file NIO/ByteBuffer-core.swift, line 357

**Comment by adam-fowler** [comment]
Ok, you've found an issue with Swift NIO there when ByteBuffers get too large, but this is also an issue with Soto where it isn't freeing the memory for previously uploaded parts of the request. I have submitted another fix which clears out the already read parts of the byte buffer.

As an aside you could write your `AWSPayload.stream` a lot simpler
```swift
    var bb = ByteBuffer(data: data)
    let payload = AWSPayload.stream(size: bb.readableBytes) { eventLoop in 
        print("Sending chunk at \(bb.readerIndex)")
        let len = min(chunkSize, bb.readableBytes)
        let chunk = bb.readSlice(length: len)!
        return eventLoop.makeSucceededFuture(.byteBuffer(chunk))
    }
```

I'm sorry you are finding so many issues.

**Comment by rnikander** [comment]
No problem, it's great that you are fixing them so quickly. And thanks for that tip on the ByteBuffer API.

**Comment by adam-fowler** [comment]
Can I ask an unrelated question? If Soto V5 only supported Catalina or later would that be an issue for you?

**Comment by rnikander** [comment]
I’d be fine with that.
