### ISSUE TITLE
putObject using keys that contain a '+' causes a signatureDoesNotMatch error

### ISSUE THREAD

**Issue by ryanbooker** [soto-project/soto#438]
**Describe the bug**
putObject using keys that contain a '+' causes a signatureDoesNotMatch error.

**To Reproduce**
1. Try to putObject with a key containing '+'

**Expected behavior**
It works.

**Setup (please complete the following information):**
 - OS: 14.2
 - Version of aws-sdk-swift: 4.9.0
 - Authentication mechanism S3 using IAM access key and secret

e.g. "tes+t.txt" with fail, but "test.txt" will succeed.

Any advice on what I'm doing wrong would be greatly appreciated. Both keys work using awscli.

**Comment by adam-fowler** [comment]
Yep this is a known issue which is fixed in the 5.0.0 beta. We are about to release the RC candidate for v5. Would you be willing to wait for the v5 release, or move up to the RC candidate now?

**Comment by ryanbooker** [comment]
Ah excellent. I'll have a look. That is a possible solution yes. Cheers.

**Comment by adam-fowler** [comment]
Here's a little guide to upgrading https://github.com/soto-project/soto/blob/5.x.x-docs/documentation/Upgrading%20to%20v5.md

**Comment by ryanbooker** [comment]
Thanks. It was very straightforward, I updated before even seeing your link. :) Everything working now. I look forward to the RCs. :)
