### ISSUE TITLE
[Question] AWSClient Shutdown best practices for long running server-side processes like Vapor

### ISSUE THREAD

**Issue by bitwit** [soto-project/soto#439]
I'm trying to get a better understanding of how to best use the AWS client for my server-side application. I started by setting up and tearing down a client for each request, but it is cumbersome and downright ugly at times to wedge a shutdown operation into the event loop chain while handling a response.

It seems like I'd be best off to create a new client at startup (or lazily loaded on the first request) and leave it allocated indefinitely for sharing across all futures request, but I'm not sure if there are potential downsides to this

Thank you

**Comment by adam-fowler** [comment]
Are you using Soto v5 RC or Soto v4? If you are using v5 this may help https://github.com/soto-project/soto/blob/5.x.x-docs/documentation/Using%20Soto%20with%20Vapor.md

**Comment by bitwit** [comment]
Thank you, yes this is perfect. Not sure how I missed this in the docs 🤦‍♂️

**Comment by adam-fowler** [comment]
It's in the 5.x.x docs which aren't released yet

**Comment by bitwit** [comment]
You're giving me the benefit of the doubt @adam-fowler. That's where I'd been looking but in the AWS Client and Services section (where I also noticed some spiffy new info about signing a PUT object url ☺️)

Looking forward to the 5.0 release!
