### ISSUE TITLE
Amazon S3 Transfer Acceleration is supported?

### ISSUE THREAD

**Issue by nastasiupta** [soto-project/soto#440]
@adam-fowler is Amazon S3 Transfer Acceleration supported by your SDK?

**Comment by adam-fowler** [comment]
I haven't tested it. Given it is an option on the console I imagine it just works. Would you be able to verify?

**Comment by adam-fowler** [comment]
@nastasiupta did you find out if it worked?

**Comment by nastasiupta** [comment]
Yes @adam-fowler

**Comment by adam-fowler** [comment]
@nastasiupta I have added an option to construct the transfer accelerated endpoints internally. Create a new S3 object from your original and use that instead of supplying your own endpoint.
```swift
let s3Accelerated = s3.with(options: .s3UseTransferAcceleratedEndpoint)
```
