### ISSUE TITLE
Signing a URL (Problems with ElasticsearchService)

### ISSUE THREAD

**Issue by cshadek** [soto-project/soto#450]
**Describe the bug**
We are trying to sign a URL for Elasticsearch.

When you sign a URL with a query parameter that includes special a special character [ ( ) % :  ... etc] , the signed URL always results in:

```
The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Also, it looks like the internal signUrl method might not follow the correct encoding steps linked below.

When we do encode the characters beforehand, we get this error.

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/groups/_search]
 contains unrecognized parameters: [X-Amz-Algorithm], [X-Amz-Credential], [X-Amz-Date],
 [X-Amz-Expires], [X-Amz-Signature], [X-Amz-SignedHeaders]"}],"type":"illegal_argument_exception",
"reason":"request [/groups/_search] contains unrecognized parameters: [X-Amz-Algorithm],
 [X-Amz-Credential], [X-Amz-Date], [X-Amz-Expires], [X-Amz-Signature], [X-Amz-SignedHeaders]"},"status":400}
```

https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

For example, it doesn't look like it double encodes the "=" characters in the added query parameters’ names and values.

**To Reproduce**
1. Create a url with a query parameter that includes a special character `(?q=%20HELLO:WORLD)`
2. Sign that url using the signURL method.

**Expected behavior**
The url should work like the unsigned url.

**Setup (please complete the following information):**
 - OS: [e.g. Vapor MacOS]
 - Version of aws-sdk-swift [e.g. 5.0]
 - Authentication mechanism: hard-coded credentials (AWS Access Key and Secret Key)

**Additional context**
We are trying to sign a URL for AWSElasticsearchService if that helps!  The unsigned url works.  Our S3 signing works and it's using the same signing key.

**Comment by adam-fowler** [comment]
Are you using `ElastisearchService.signURL` or are you having problems with the signer while using `ElastisearchService` commands? You shouldn't percent encode the characters beforehand. The signer cannot tell if it is receiving percent encoded text of not, so it assumes everything is unsigned. If you are getting a signing issue then that is an issue with the signer. 

Can you provide a URL that isn't getting signed correctly and the code you using to sign it please. So far all the query parameters I have signed all seem to work.

**Comment by adam-fowler** [comment]
Currently `signURL` assumes a number of things as it used to expect "clean" URLs generated by `AWSRequest`.

- queries are sorted by query parameter name
- queries are percent encoded. AWS expects everything to be percent encoded except alphanumeric characters and "-_.~".

I can do some of this work inside `signURL` now.

**Comment by adam-fowler** [comment]
I had a closer look at this. Once you have a properly signed URL the error you are hitting is related to the fact that the signed URL query parameters are being passed along to ElasticSearch. It then tries to parse them and errors because it doesnt recognise them. 

So what you need to do is make a request with signed header values instead of a signed URL. Up to this point there hasn't been an easy method for generating these, without digging into the internals of Soto. I have add a new method `AWSClient.signHeaders` on the `signing-fixes` branch of soto-core. You would sign a request as follows

```swift
let es = ElasticsearchService(client: awsClient, region: .euwest1)
let responseFuture = es.signHeaders(url: url, httpMethod: .GET, headers: headers)
    .flatMap { headers in
        let request = try HTTPClient.Request(url: url, method: .GET, headers: headers)
        return httpClient.execute(request: request, deadline: .now() + .minutes(5))
    } 
let response = try responseFuture.wait()
```
The branch `signing-fixes` also percent encodes any URLs sent to the `signURL` and `signHeaders` functions so the initial issue you were having should also be resolved.

Can you verify this branch fixes the issues you are having

**Comment by cshadek** [comment]
Thank you so much for your quick response!  This looks perfect!  We will try the signHeaders function and will let you know if that works.

**Comment by cshadek** [comment]
It worked great!  Thank you so much!

**Comment by cshadek** [comment]
> I had a closer look at this. Once you have a properly signed URL the error you are hitting is related to the fact that the signed URL query parameters are being passed along to ElasticSearch. It then tries to parse them and errors because it doesnt recognise them.
> 
> So what you need to do is make a request with signed header values instead of a signed URL. Up to this point there hasn't been an easy method for generating these, without digging into the internals of Soto. So I have add a new method `AWSClient.signHeaders` on the `signing-fixes` branch of soto-core. You would sign a request as follows
> 
> ```swift
> let es = ElasticsearchService(client: awsClient, region: .euwest1)
> let responseFuture = es.signHeaders(url: url, httpMethod: .GET, headers: headers)
>     .flatMap { headers in
>         let request = try HTTPClient.Request(url: url, method: .GET, headers: headers)
>         return httpClient.execute(request: request, deadline: .now() + .minutes(5))
>     } 
> let response = try responseFuture.wait()
> ```
> 
> The branch `signing-fixes` also percent encodes any URLs sent to the `signURL` and `signHeaders` functions so the initial issue you were having should also be resolved.
> 
> Can you verify this branch fixes the issues you are having

Do the signURL and signHeaders functions also properly encode the path?  I tried adding a `*` or `,` in the path (I'm trying to search across multiple indices), but then I get the ``` The request signature we calculated does not match the signature you provided``` error again.

**Comment by adam-fowler** [comment]
Do you want to try latest? I think that should work now. Trying to cover every situation in the signer is quite painful

**Comment by cshadek** [comment]
I'm still getting the same error: ```The request signature we calculated does not match the signature you provided error again.```

I noticed here https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html:

2. Normalize URI paths according to RFC 3986. Remove redundant and relative path components. Each path segment must be URI-encoded twice (except for Amazon S3 which only gets URI-encoded once).  

Is this happening in the signer currently?

**Comment by adam-fowler** [comment]
Can you provide the URL you are having problems with.

**Comment by cshadek** [comment]
Here is the path and query components: ```/*/_search?q=*```

It works if I replace the first * with a name of an index (user-index, etc)

**Comment by cshadek** [comment]
It also gives the same problem if I put a "," in the path.

**Comment by cshadek** [comment]
Also, I just noticed (I was testing several special characters).  If you include a `#` in the query string it causes the same error.

**Comment by adam-fowler** [comment]
@cshadek Are you sure you are running with the latest code? I have just tested all of these and they work. How are you bringing the soto-core signing-fixes branch into your project?

**Comment by cshadek** [comment]
I think I'm using the latest.  This is what I have in my Package.swift file:

```
.package(url: "https://github.com/soto-project/soto-core.git", .branch("signing-fixes")),
.package(url: "https://github.com/soto-project/soto.git", from: "5.0.0"),
```

Is there a better way to specify that I want the "signing-fixes" branch.

**Comment by adam-fowler** [comment]
Not sure how SPM would load that. As Soto.git will try to bring in the 5.0.0 version of Soto-core. 

When I want to bring in a copy of Soto-core I drag a copy of the local version into XCode. It then replaces the one it loaded through SPM. See the Editing a local copy section in this article https://useyourloaf.com/blog/editing-a-swift-package/

**Comment by cshadek** [comment]
It did bring in the signHeaders function.  That’s not in the master branch right?

**Comment by cshadek** [comment]
> Not sure how SPM would load that. As Soto.git will try to bring in the 5.0.0 version of Soto-core.
> 
> When I want to bring in a copy of Soto-core I drag a copy of the local version into XCode. It then replaces the one it loaded through SPM. See the Editing a local copy section in this article https://useyourloaf.com/blog/editing-a-swift-package/

Is this possible to do, given that we are using Docker?

**Comment by cshadek** [comment]
> Not sure how SPM would load that. As Soto.git will try to bring in the 5.0.0 version of Soto-core.
> 
> When I want to bring in a copy of Soto-core I drag a copy of the local version into XCode. It then replaces the one it loaded through SPM. See the Editing a local copy section in this article https://useyourloaf.com/blog/editing-a-swift-package/

Ok so I instead changed the Package.swift code to use:

```
.package(url: "https://github.com/soto-project/soto-core.git", .revision("a68afd448b6a29def945c7e560b86883545d2ff6")),
.package(url: "https://github.com/soto-project/soto.git", from: "5.0.0"),
```

This seems to work.

**Comment by adam-fowler** [comment]
> It did bring in the signHeaders function. That’s not in the master branch right?

I guess it hadn't updated to the latest version of the branch. When depending on a branch you have to run `swift package update` to ensure you have the latest code.

> Is this possible to do, given that we are using Docker for production?

This would not work for production. It would only ever be used to test something in development.

Any way if things are working I'll merge that PR into `main` and it'll be in the next release
