### ISSUE TITLE
Support developer authenticated cognito identities

### ISSUE THREAD

**Issue by someshkarthik** [soto-project/soto#452]
```swift
let credential: CredentialProviderFactory = .cognitoIdentity(identityPoolId: "id", logins: [ "cognito-identity.amazonaws.com" : "token received from server"],region: .useast1)

let client = AWSClient(credentialProvider: credential, httpClientProvider: .createNew)
```

This is how I initiate an AWS client to perform upload with S3. But I received this error `NotAuthorizedException: Invalid login token. Can't pass in a Cognito token.` when I try to upload a video.

Also there is no param for `IdentityId` when initializing AWS client with CognitoIdentity.

@adam-fowler

**Comment by adam-fowler** [comment]
If you are using cognito userpools for identity your code should look as follows
```swift
let userPoolId = "my user pool id"
let identityPoolId = "my identity pool id"
let identityProvider = "cognito-idp.us-east-1.amazonaws.com/\(userPoolId)"
let credential: CredentialProviderFactory = .cognitoIdentity(
    identityPoolId: identityPoolId, 
    logins: [ identityProvider : "id token received from server"], 
    region: .useast1
)

let client = AWSClient(credentialProvider: credential, httpClientProvider: .createNew)
```

You don't need to provide the `IdentityId` parameter as we can get that from AWS using `CognitoIdentity.getId()`.

**Comment by someshkarthik** [comment]
No, We are using federated identities

**Comment by adam-fowler** [comment]
Yeah but who is your identity provider?

**Comment by jprassanakumar** [comment]
Hi @adam-fowler ,
I am working with @someshkarthik .
We are using custom provider in federated identities.

**Comment by adam-fowler** [comment]
Ok looks like we don't suppport developer authenticated identities as we are assuming we will get the `IdentityId` from `CognitoIdentity.getId()` and not from an id returned by a developer server. I will look to see if I can add support.

**Comment by someshkarthik** [comment]
Ok. Thank you. Please add support for the custom provider. Looking forward to it.

**Comment by adam-fowler** [comment]
Can you see if #453 works for you. 

You provide a structure conforming to `IdentityProvider` which has function `getIdentity` which returns `EventLoopFuture<IdentityParams>`. `IdentityParams` consists of identityId and logins required by `GetCredentialsForIdentity`.

**Comment by someshkarthik** [comment]
Will check now.

**Comment by someshkarthik** [comment]
It worked @adam-fowler. Thanks a lot.

**Comment by adam-fowler** [comment]
If you do that call to your server inside the `getIdentity()` function, the credentials will get renewed whenever they are about to expire.
