### ISSUE TITLE
Upload failed with multipart upload

### ISSUE THREAD

**Issue by someshkarthik** [soto-project/soto#454]
**Describe the bug**
Upload failed when tried to upload a video file using multipart upload using `S3.CreateMultipartUploadRequest`. 

**Code Snippet** 
``` swift
let bucket = "my bucket name"
let key = "15006472.mp4"
let s3 = S3(client: client, region: .useast1)
let uploadRequest = S3.CreateMultipartUploadRequest(bucket: bucket, key: key)
s3.multipartUpload(uploadRequest, partSize: 5*1024*1024, filename: videoURL.path, abortOnFail: false) { (progress) in
     print(progress)
}.always { (result) in
     switch result {
     case let .success(output):
           print(output)
     case let .failure(error):
           print(error)
     }
}
```

**Error Message from SDK**
``` swift 
dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "x-amz-abort-date", intValue: nil)], debugDescription: "Date string does not match format expected", underlyingError: nil))
```

**Response SDK received From AWS(`https://bucket_name.s3.us-east-1.amazonaws.com/15006472.mp4?uploads=`)**
``` xml
<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
	<Bucket>bucket name</Bucket>
	<Key>15006472.mp4</Key>
	<UploadId>some upload id</UploadId>
</InitiateMultipartUploadResult>
```

**Expected behavior**
I should receive a success message on a successful upload

**Setup (please complete the following information):**
 - OS: MacOS
 - Version of soto: 5.0.0
 - Authentication mechanism: hard-coded credentials

@adam-fowler

**Comment by adam-fowler** [comment]
I guess you have a lifecycle rule on your S3 bucket to remove old unfinished multipart upload parts.

Without looking at the code I'm guessing I'm parsing the abort date associated with the lifecycle rule as a iso8601 date instead of a http header date.

**Comment by adam-fowler** [comment]
Can you test branch `s3-multipart-upload-abort-date` to see if this fixes your issue 

thank you

**Comment by someshkarthik** [comment]
Will check `s3-multipart-upload-abort-date` and let you know. thank you.

**Comment by someshkarthik** [comment]
It worked. Thank you so much @adam-fowler

**Comment by adam-fowler** [comment]
You should be able to set the endpoint when initializing your S3 object. If you point it at the accelerated endpoint it should work. I haven't tested this but I have had other users say it works.

I do have additional work setup for uploading more than one multipart part at the same time.

**Comment by adam-fowler** [comment]
@someshkarthik because someone else also asked I have added an option to construct the transfer accelerated endpoints. Create a new S3 object from your original
```swift
let s3Accelerated = s3.with(options: .s3UseTransferAcceleratedEndpoint)
```

You'll find this on the `main` branch
