### ISSUE TITLE
Multiple MultipartUploadRequest causing memory spike

### ISSUE THREAD

**Issue by nastasiupta** [soto-project/soto#463]
**Is your feature request related to a problem? Please describe.**
I want to do at least 5 images uploading at the same time. I'm making only one S3 instance with AWS configuration. The issue is that when I start the requests using `s3.multipartUpload`, the memory spikes to 800mb-1GB. Also, I want to mention that I need to get the progress for each request, to display it to the user.

**Describe the solution you'd like**
How can I do it more efficiently? Minimum memory usage... because in the future I want to support dynamic number, considering user uploading speed.

**Describe alternatives you've considered**
For now, just 1 file at a time... which is not nice.

**Comment by adam-fowler** [comment]
Hi @nastasiupta I have to admit I haven't tested memory usage during a multipart upload, but it has been designed to have as little impact as possible so am surprised you are seeing 1GB peaks.

Can you give me a little more information about the size of file you are uploading

**Comment by nastasiupta** [comment]
Hey @adam-fowler, well, the images are small about 1mb up to 3-4mb... Those files are not very big... In the future, we plan to support maximum of 15mb images uploading. It's pretty strange what happens with the momery during the upload but after the upload is ready it goes back to a normal level... not the initial one before, even I deallocate the uploading workers.

**Comment by adam-fowler** [comment]
Wow something is going wrong there. 

There is no point using multipart for files smaller than 5mb though as that is the smallest size an individual part can be.

**Comment by adam-fowler** [comment]
What is the source for these images? Are they files, or are they already in memory?

**Comment by nastasiupta** [comment]
So the project is a macOS app, and the files are selected by the user (importing to the app using NSOpenPanel

**Comment by nastasiupta** [comment]
> Wow something is going wrong there.
> 
> There is no point using multipart for files smaller than 5mb though as that is the smallest size an individual part can be.

Well, the users will upload bigger files, between 10-15mb.. I use those small files for testing...

**Comment by adam-fowler** [comment]
So I've looked at memory while running the S3Tests.testMultiPartUpload() test and it never seems to use much more than 2mb while loading a 11mb file. How are you measuring memory usage?

Does you upload code look like this?
```swift
let request = S3.CreateMultipartUploadRequest(
    bucket: name,
    key: name
)
return s3.multipartUpload(request, filename: filename)
```

**Comment by nastasiupta** [comment]
> So I've looked at memory while running the S3Tests.testMultiPartUpload() test and it never seems to use much more than 2mb while loading a 11mb file. How are you measuring memory usage?
> 
> Does you upload code look like this?
> 
> ```swift
> let request = S3.CreateMultipartUploadRequest(
>     bucket: name,
>     key: name
> )
> return s3.multipartUpload(request, filename: filename)
> ```

Yes it does... I changed partSize to 8mb instead of default values of 5mb ...
Do you observe the progress? what about the always event to know when is ready or it had an issue?
 { (progress) in ... }
and
_ = multipartUpload.always { (uploadResult) in
....

**Comment by adam-fowler** [comment]
Regarding progress. If uploading a file the progress callback gets called for every 64K being uploaded. So you could update a UI and see fairly smooth progress. You can also throw an error from the progress callback to cancel the operation.

**Comment by adam-fowler** [comment]
When you are seeing the 1GB memory usage can you use the Xcode memory graph hierarchy to verify what is allocating all the memory.

**Comment by adam-fowler** [comment]
@nastasiupta ?

**Comment by nastasiupta** [comment]
Fixed... I updated the UI each time I had uploaded progress and it looks like SwiftUI is deallocated memory after a few seconds, not instant as I expected when the view body is reloaded... Sorry for rising the issue. You can delete it :)

**Comment by adam-fowler** [comment]
Gotta love SwiftUI :-)
