### ISSUE TITLE
Aurora Serverless Cluster ARNs can have more than 100 characters.

### ISSUE THREAD

**Issue by DwayneCoussement** [soto-project/soto#471]
**Describe the bug**
Aurora Serverless Cluster ARNs can have more than 100 characters.

**Suggestion**
Change the max length to 2048 https://docs.aws.amazon.com/IAM/latest/APIReference/API_Policy.html

**To Reproduce**
1. Create a new aurora serverless cluster (via CDK for example)

```    
    const vpc = new ec2.Vpc(this, 'SotoVPC');
    const dbName = 'SotoDB';
    const cluster = new rds.ServerlessCluster(this, 'SotoCluster', {
      engine: rds.DatabaseClusterEngine.AURORA_POSTGRESQL,
      parameterGroup: rds.ParameterGroup.fromParameterGroupName(this, 'ParameterGroup', 'default.aurora-postgresql10'),
      defaultDatabaseName: dbName,
      vpc
    });
```
2. fetch clusterArn via `cluster.clusterArn`
3. Make a request:
```
let query = RDSDataService.ExecuteStatementRequest(database: "SotoDB", resourceArn: clusterArn, secretArn: secretArn)
self.rds.executeStatement(query).wait()
```
4. Notice you get a validation error:
ValidationError: Length of ExecuteStatementRequest.resourceArn (101) is greater than the maximum allowed value 100.

**Expected behavior**
Don't make an assumption on that the ARN will be less than 100

**Setup (please complete the following information):**
 - OS: Amazon Linux2
 - Version of soto: 5.2
 - Authentication mechanism [hard-coded credentials, IAM Instance Profile on EC2, etc]

**Additional context**
Add any other context about the problem here. If this a bug related to a command not working can you run the same command on a client initialised with the logging middleware. eg `S3(region: .useast1, middlewares:[AWSLoggingMiddleware()])`

**Comment by adam-fowler** [comment]
#473
