### ISSUE TITLE
SignUrl does not seem to be working correctly for S3.PutObject

### ISSUE THREAD

**Issue by cshadek** [soto-project/soto#477]
**Describe the bug**
SignURL does not seem to be working for signing a url for an S3.PutObject request.  It's possible I have made an error.  The code is included below.  My goal is to be able to send the client a signed URL so the client can upload a file directly.

**To Reproduce**

Replace BUCKET with a bucket name.
```
let fileKey = UUID().uuidString.replacingOccurrences(of: "-", with: "")
let unsignedUrlString = "https://BUCKET.s3.amazonaws.com/\(fileKey)?Content-Type=image/jpeg"
let unsignedUrl = URL(string: unsignedUrlString)!
let components = URLComponents(url: unsignedUrl, resolvingAgainstBaseURL: false)!
let urlString = "\(components.scheme!)://\(components.host!)\(components.path.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed)!)?\(components.query!.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)"
let url = URL(string: urlString)!

return request.aws.s3.signURL(url: url, httpMethod: .PUT, expires: .hours(1))
```

**Expected behavior**
My goal is to be able to send the client a signed URL so the client can upload a file directly.  I expect the signed url to work.  When I attempt to upload a file using the signed URL I get the following:

```The request signature we calculated does not match the signature you provided. Check your key and signing method.```

**Setup (please complete the following information):**
 - OS: MacOS or Linux (Vapor)
 - Version of soto: 5.1.0

**Comment by adam-fowler** [comment]
I just ran your code and it works. The only thing I could see going wrong here is if your client didn't use the PUT method. 

By the way you don't need all the URL parsing code. It is all done for you. Your code should be able to reduce down to 
```swift
let fileKey = UUID().uuidString.replacingOccurrences(of: "-", with: "")
let unsignedUrlString = "https://BUCKET.s3.amazonaws.com/\(fileKey)?Content-Type=image/jpeg"
let unsignedUrl = URL(string: unsignedUrlString)!
return request.aws.s3.signURL(url: unsignedUrl, httpMethod: .PUT, expires: .hours(1))
```

**Comment by adam-fowler** [comment]
Also if you want the `Content-type` set, get the client to do it with a header ["Content-Type": "image/jpeg"]. Doing it as a query parameter doesn't work. The client should be able to add a header value without breaking the signing, although I would get the upload working on its own without the content-type first.

**Comment by cshadek** [comment]
You were right!  I was using POST from the client.  And it's nice not to have to include the url parsing code.  Thanks for responding so quickly.
