### ISSUE TITLE
Cognito list users fails for EXTERNAL_USERS

### ISSUE THREAD

**Issue by t089** [soto-project/soto#478]
**Describe the bug**
Cognito `listUsers` fails with a decoding error for user pools with users associated to an external identity provider.

**To Reproduce**
1. Given a Cognito User Pool with users from an external identity provider (eg. Google), the `listUsers` methods throws an error.

```
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "Users", intValue: nil), _DictionaryKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "UserStatus", intValue: nil)], debugDescription: "Cannot initialize UserStatusType from invalid String value EXTERNAL_PROVIDER", underlyingError: nil))
```

Indeed, `EXTERNAL_PROVIDER` is missing in [`UserStatusType`](https://github.com/soto-project/soto/blob/f535e52715069125f72b109e0c1032364accfff8/Sources/Soto/Services/CognitoIdentityProvider/CognitoIdentityProvider_Shapes.swift#L260-L269):
https://github.com/soto-project/soto/blob/f535e52715069125f72b109e0c1032364accfff8/Sources/Soto/Services/CognitoIdentityProvider/CognitoIdentityProvider_Shapes.swift#L260-L269

**Expected behavior**
List users should work.

**Setup (please complete the following information):**
 - OS: macOS
 - Version of soto: 
 ```
  {
        "package": "soto",
        "repositoryURL": "https://github.com/soto-project/soto.git",
        "state": {
          "branch": null,
          "revision": "f5b1610fe320d81160bc2079317a4e89e7fb6d51",
          "version": "5.2.0"
        }
      },
      {
        "package": "soto-core",
        "repositoryURL": "https://github.com/soto-project/soto-core.git",
        "state": {
          "branch": null,
          "revision": "4b19caaf8645726949f299209ec0b4902d347c43",
          "version": "5.1.2"
        }
      },
```
 - Authentication mechanism cognito identity provider

**Comment by t089** [comment]
By the way, would be a good idea to convert the `enums` into `RawRespresentable` `structs` that can also decode unknown values instead of just failing.


Something like this

```
struct UserStatusType: RawRepresentable, Codable, Equatable {
    let rawValue: String
    static let archived = UserStatusType(rawValue: "ARCHIVED")
}
```

?

**Comment by adam-fowler** [comment]
@t089 I use `RawRepresentable` for enums that change often. I would prefer we kept to `enums` where we can.

**Comment by adam-fowler** [comment]
#479

**Comment by t089** [comment]
> @t089 I use `RawRepresentable` for enums that change often. I would prefer we kept to `enums` where we can.

I will open a new issue to discuss this in a bit more detail 😅

Thanks for the fix 👍
