### ISSUE TITLE
Wrong HTTPMethod when signed url

### ISSUE THREAD

**Issue by Linkadi98** [soto-project/soto#486]
**Describe the bug**
I used signURL function to sign my s3 bucket url with POST method, but when returning the signed url back to client, I initialized an URLRequest with that url, debug console gave me a weird result that the HTTPMethod is GET, not the POST method in signed url.

**To Reproduce**
Just use the signURL function from S3 to sign an simple url, nothing much
**Expected behavior**
Signed url will have correct HTTPMethod

**Setup (please complete the following information):**
 - OS: MacOS Bigsur
 - Version of soto: latest
 - Authentication mechanism: hard-coded credentials

**Comment by adam-fowler** [comment]
Is the URLRequest setup to use POST. I think it defaults to GET

**Comment by Linkadi98** [comment]
When I set POST method for URLRequest instance, URLSession gives me an error that is the httpMethod was set, so I leave the httpMethod of URLRequest to nil, just init the URLRequest with the signed url, and later I debug this URLRequest instance and it gives me httpMethod is GET

**Comment by Linkadi98** [comment]
Plus I don't set any default httpMethod for URLRequest

**Comment by adam-fowler** [comment]
From https://developer.apple.com/documentation/foundation/urlrequest/2011415-httpmethod
> The default HTTP method is “GET”.

A URL doesn't store the HTTP method, you need to set it elsewhere.

Which of the many `URLSession` functions are you calling. Checkout John Sundell's article on using POST. https://www.swiftbysundell.com/articles/http-post-and-file-upload-requests-using-urlsession/

**Comment by Linkadi98** [comment]
Thank you for pointing it! 

I'm going to check it
