### ISSUE TITLE
Secrets Manager

### ISSUE THREAD

**Issue by akun1** [soto-project/soto#495]
Support for making AWS SM requests would be nice! 😃

**Comment by adam-fowler** [comment]
Does the Soto library SotoSecretsManager not provide what you need?

Amazon even used it in a sample. https://github.com/aws-samples/aws-serverless-fullstack-swift-apple-carplay-example/blob/main/cdk/lambda/functions/get-weather/Sources/get-weather/main.swift

**Comment by akun1** [comment]
Oh jeez, my bad! Thank you!
