### ISSUE TITLE
SotoSES compile error with docker

### ISSUE THREAD

**Issue by Linkadi98** [soto-project/soto#496]
Hi @adam-fowler, 

I have used soto for AWS S3, everything works fine at local enviroment, but when deploying to server by docker, I saw that docker running command `swift build` and it stopped while compling SES_API.swift file, therefore I couldn't build docker image . Before I used Soto, I could still deploy by docker normally.

So how to fix this issue, I've tried to fix this for 2 days but no hope.

**Comment by adam-fowler** [comment]
Have you tried increasing the amount of memory available to Docker?

**Comment by Linkadi98** [comment]
Oh thanks to pointing it out. My image was built!
