### ISSUE TITLE
Unable to getBucketLocation for a bucket not in us-east-1

### ISSUE THREAD

**Issue by tomTheWolf** [soto-project/soto#509]
**Describe the bug**
Calls to `S3().listObjectsV2` are failing for buckets not in `us-east-1`. I believe I need to instantiate S3() with the proper region, however calls to `S3().getBucketLocation` are failing for the same reason (see below), so I am unable to determine what region the bucket is in.

```[ ERROR ] AuthorizationQueryParametersError: Message: Error parsing the X-Amz-Credential parameter; the region 'us-east-1' is wrong; expecting 'us-east-2', Region: us-east-2, RequestId: RY828HFR0J9BC4PS, HostId: M57G8oOMiGcx7hq+E+wRe8v1LwmhAGurRCPemx5rSTZWZ8VEuTmRMVfaeDQTrlptBp5q+E7MjJQ= (Customer 31) (DiscreetErrorMiddleware.swift:21)```

**To Reproduce**
1. Call S3().getBucketLocation on a bucket in us-east-2
2. AWS returns an error like the one above

**Expected behavior**
AWS returns information about the location of the bucket

**Setup (please complete the following information):**
 - OS: macOS
 - Version of soto: 3.5.2
 - Authentication mechanism: hard-coded credentials

**Additional context**

**Comment by adam-fowler** [comment]
V3.x of Soto isn't being supported anymore but if you are willing to make a PR to the `3.x.x` branch I will do a release for you. You can find some details in #502
