### ISSUE TITLE
File uploading issue.

### ISSUE THREAD

**Issue by Timid666** [soto-project/soto#511]
Hi. I have a problem. I used putObject method to upload file. Now i'm using multipartUpload method because i need to track upload progress to show user how much percent is uploaded. 
But the problem is both methods sometimes don't upload file. 

I.e for example in putObject method when upload is success i use listObjectsV2 method to get new files list. But new list doesn't come. But if i go to the previous view controller and make new connect again i get new files list and the file is there.

In multipartUpload method sometimes files is not upload fully and i use resumeMultipartUpload method as in the documentation. But sometimes resumeMultipartUpload method is upload a part of file and breaks too and i get "Receive failed with error "Connection reset by peer"" error. 

I need your advice ) Maybe I'm doing something wrong ))

**Comment by adam-fowler** [comment]
Hi @Timid666 can you post your code please. I'll see if I can find any issues in it

**Comment by Timid666** [comment]
Yes sure. Here.

<img width="1436" alt="Screenshot" src="https://user-images.githubusercontent.com/53529215/129338387-dc2ed7bc-5382-468f-804a-1829de2f0d79.png">

**Comment by adam-fowler** [comment]
Are you writing to an S3 like service, not AWS S3?

Before you call `listObjectsV2` are you sure the `putObject` command has finished? If you aren't using AWS S3 there might be a small amount of time between the `putObject` finishing and the object appearing in the list. You could use `S3. waitUntilObjectExists` before calling the list function. 

If `S3.resumeMultipartUpload` fails then you need to call it again, with the new `resumeRequest` returned in the error.

As an aside you can do UI progress with `S3.putObject` if you use a `AWSPayload.fileHandle`. See https://github.com/soto-project/soto/issues/510#issuecomment-897663073

**Comment by Timid666** [comment]
Yes i writing to an S3 like service. Not AWS S3.
Do you mean make new resumeRequest here in case?

<img width="1120" alt="Снимок экрана 2021-08-13 в 13 38 02" src="https://user-images.githubusercontent.com/53529215/129345076-9e0e474b-2e29-453e-af09-74eb988f527e.png">

**Comment by adam-fowler** [comment]
Add another `.flatMapError` section for how many times you want to retry the upload. Also use the `S3.waitUntilObjectExists` function after the upload has finished.

I have rarely seen that many errors. Could this be related to the service you are using? Other issues might be the upload process has been starved of CPU time and the server has closed the connection because it isn't receiving any data or the network connection between your client and the server is poor.

What platform are you running on? And what version of Soto are you using?

**Comment by thatMacAdmin** [comment]
Hey @adam-fowler when I chain the .flatMapError together, when I hit the second failure block it starts again from wherever the first failure block started.

For example let's say I am uploading a file and it errors out. I hit the .flatMapError at 25% uploaded. It then continues uploading at 25%. Then lets say at 75% it errors out and hits the second .flatMapError condition. The behavior I see is that it starts uploading at 25% again, not 75% like I would expect.

``` swift
func upload(_ file: URL, prefix: String, closure: @escaping (Result<Double, Error>) -> Void) {
        self.logger.debug("Starting object upload to backend")
        guard let credentials = self.retrieveCredentials() else {
            self.logger.error("Invalid credentials")
            return
        }
        let s3 = self.createS3Client(accessKey: credentials.username, secretKey: credentials.password)
        let request = S3.CreateMultipartUploadRequest(bucket: self.bucketList[self.environment] ?? String(),
                                                      key: "\(prefix)/\(file.lastPathComponent)")
        
        s3.multipartUpload(
            request,
            filename: file.path,
            abortOnFail: false
        ) {
            if self.cancelUpload == true {
                self.logger.info("User cancelled upload")
                throw MyError.userCancelledUpload

            }
            debugPrint("Cancel State: \(self.cancelUpload)")
            closure(.success($0))
        }
        .flatMapError { error -> EventLoopFuture<S3.CompleteMultipartUploadOutput> in
            self.logger.debug("Hit an error while uploading: \(error.localizedDescription)")
            
            switch error {
            case S3ErrorType.multipart.abortedUpload(resumeRequest: let resumeRequest, error: _):
                self.logger.error("Re-upload attempt 01")
                return s3.resumeMultipartUpload(resumeRequest, filename: file.path, abortOnFail: false) {
                    
                    if self.cancelUpload {
                        self.logger.debug("User cancelled upload")
                        throw MyError.userCancelledUpload
                    }
                    
                    closure(.success($0))
                }
            default:
                self.logger.error("Hit an error we cannot recover from.")
                return s3.eventLoopGroup.next().makeFailedFuture(error)
            }
        }
        .flatMapError { error -> EventLoopFuture<S3.CompleteMultipartUploadOutput> in
            self.logger.debug("Hit an error while uploading: \(error.localizedDescription)")
            
            switch error {
            case S3ErrorType.multipart.abortedUpload(resumeRequest: let resumeRequest, error: _):
                self.logger.error("Re-upload attempt 02")
                return s3.resumeMultipartUpload(resumeRequest, filename: file.path, abortOnFail: false) {
                    
                    if self.cancelUpload {
                        self.logger.debug("User cancelled upload")
                        throw MyError.userCancelledUpload
                    }
                    
                    closure(.success($0))
                }
            default:
                self.logger.error("Hit an error we cannot recover from.")
                return s3.eventLoopGroup.next().makeFailedFuture(error)
            }
        }
        .whenComplete { result in
            switch result {
            case .success:
                self.logger.info("Upload succeeded")
                closure(.success(1.0))
                s3.client.shutdown(queue: .main) { shutdown in }
            case .failure(let error):
                self.logger.error("\(error)")
                closure(.failure(error))
                s3.client.shutdown(queue: .main) { shutdown in }
            }
        }
    }
```

**Comment by adam-fowler** [comment]
To do a repeating until fail upload you could do something like this
```swift
func resume(
    _ resumeRequest: S3.ResumeMultipartUploadRequest, 
    on eventLoop: EventLoop
) -> EventLoopFuture<S3.CompleteMultipartUploadOutput> {
    let promise = eventLoop.makePromise(of: S3.CompleteMultipartUploadOutput.self)
    func _resume(_ resumeRequest: S3.ResumeMultipartUploadRequest) {
        s3.resumeMultipartUpload(resumeRequest, filename: file.path, abortOnFail: false) { _ in
        }
        .flatMapError { error in
            switch error {
            case S3ErrorType.multipart.abortedUpload(resumeRequest: let resumeRequest, error: _):
                _resume(resumeRequest)
            default:
                promise.fail(error)
            }
        }
        .whenSuccess { response in
            promise.succeed(error)
        }
    }
    _resume(resumeRequest)
    return promise.futureResult
}
```

**Comment by adam-fowler** [comment]
I'll have a look at the second resume redoing the same work

**Comment by adam-fowler** [comment]
You were right the second resume was using the completed parts array sent to the original resume. PR https://github.com/soto-project/soto/pull/515 should fix this as it throws a new resume request with updated completedParts. You will still see the percent value go down slightly as the `resumeUpload` can only start on part boundaries, but you won't be seeing anything like a jump from 75% to 25%.

Can you verify this PR fixes the issue?

**Comment by thatMacAdmin** [comment]
In my initial test using the code above, it actually now seems to start from 0% on all flatMapError blocks. Ill take a look today and see if I can step through it. Possible im just missing something silly in my implementation.

**Comment by adam-fowler** [comment]
> I will take a look at your promise based resume solution. Is that something that would be fired from the .flatMapError block?

Yes
