### ISSUE TITLE
Codable extension for Aurora

### ISSUE THREAD

**Issue by patagoniacode** [soto-project/soto#512]
**Description**
- When using Soto for interacting with the Aurora Serverless V1 Data API, I would like to call the RDSDataService.executeStatement method and receive a JSON object and also be able to decode the response to a Swift Object.
- Currently, the return type of the expression RDSDataService.executeStatement(statement).records is of type [[RDSDataService.Field]].

**Describe the solution you'd like**
- Receive or transform the RDSDataService.ExecuteStatementResponse.records as a JSON object and as a Swift object.
- Ideally have a solution similar to the Soto DynamoDB Codable extension, described here: https://soto.codes/user-guides/dynamodb-and-codable.html

**Additional context**
<img width="1381" alt="Screenshot" src="https://user-images.githubusercontent.com/72701635/129457054-a0b888e4-70ff-4683-9596-9657aafdcdab.png">
- In this example, I would like to be able to transform the response of type [[RDSDataService.Field]] to the Product object.

Thank you for your help.

**Comment by adam-fowler** [comment]
What you are asking for is not a small amount of work. I'm ready to accept a PR for this and happy to give guidance on what would be expected.

**Comment by patagoniacode** [comment]
Hi @adam-fowler, I made a pull request. This is my first PR, so any guidance would be highly appreciated.
