### ISSUE TITLE
After some time of usage AWS client reports "No credential provider found"

### ISSUE THREAD

**Issue by t089** [soto-project/soto#514]
**Describe the bug**
I am using `AWSClient` in production in an AWS EKS k8s cluster. The service uses `AWSClient` to access `S3`. The only call I do is: `s3.getObjectStreaming(...)`.

The service runs smoothly and is handling around ~ 5 req/s (peak 40 req/s) over the day. I have three replicas running. After _some time_ one of the pods suddenly reports an error on every request: `No credential provider found`. 

The `AWSClient` and `S3` instances are created globally like this:
```swift
let awsClient = AWSClient(credentialProvider: .selector(.environment, .ecs, .ec2, .stsWebIdentityTokenFile(region: awsRegion), .configFile()), httpClientProvider: .shared(httpClient), logger: logger)
lifecycle.registerShutdown(label: "AWS-Client", .sync(awsClient.syncShutdown))
let s3Client = S3(client: awsClient, region: awsRegion)
```

In the cluster the primary auth mechanism is `.stsWebIdentityTokenFile`.

When the pod fails with the given error message, I can verify that the web identity token file is in fact present on the pod and contains valid credentials. A restart of the troublesome pod "fixes" the issue.

**Setup (please complete the following information):**
 - OS: Build `swift:5.4-focal`, Runtime: `ubuntu:20.04`
 - Version of soto: `5.6.0`
 - Authentication mechanism: `stsWebIdentityTokenFile`

I will try to enable more verbose logging, to see why the authentication chain is failing.

**Comment by adam-fowler** [comment]
@t089 Is this when the token needs to refresh? There will be a debug log "Refeshing AWS credentials" at that point. Would be useful to know if a refresh was ever successful if you do get a failure at that point.

Unfortunately I don't have any logging actually inside the `AssumeRoleWithWebIdentityTokenFileCredentialProvider`. If you run your own version of soto you could add log entries for the loading of the file in `AssumeRoleWithWebIdentityTokenFileCredentialProvider.loadTokenFile`.

**Comment by t089** [comment]
Thanks for the pointers, I've added lots of log statements for now [here](https://github.com/t089/soto/commit/7100b23f115898755789c10d82155b1ca5c13ee0). When it happens again, I might have more information. 🤞

**Comment by adam-fowler** [comment]
Maybe add 
```swift 
.flatMapErrorThrowing { error in
    logger.debug("Error: \(error)")
    throw error
}
```
At the end of the `requestProvider.request` chain

**Comment by t089** [comment]
👍

**Comment by t089** [comment]
I have not observed this behaviour again. I will close this issue for now.
