### ISSUE TITLE
Make CognitoIdentityProvide.SignUpResponse Codable, rather than just Decodable.

### ISSUE THREAD

**Issue by majortom64** [soto-project/soto#531]
If it is Codable, it should work with an extension to make it Content.

**Comment by adam-fowler** [comment]
As I said on Discord I am not ready to do this. Making response structs `Codable` means generating more code and given the number of response structs in Soto that would be a large amount of code which in general is never used. 

If you want to encode the data from the `SignUpResponse` move it into your struct which is `Codable`.
