### ISSUE TITLE
Can list buckets in Digital Ocean Spaces, but unable to write/read a file into a bucket

### ISSUE THREAD

**Issue by Jauzee** [soto-project/soto#572]
I tried my best searching this topic but didn't find anything useful.

**Describe the bug**
I can list my buckets on DO Spaces, but can not read or write individual files.

**To Reproduce**
1. Create S3 connection object.
2. Make request to read or write a file.
<img width="658" alt="snap" src="https://user-images.githubusercontent.com/7991920/148853947-300b0f78-0ab8-404b-9f3a-3e515b2d273d.png">

The file is there and accessible for public read. I have also tried to write a file into different buckets, no success.
<img width="590" alt="Screenshot 2022-01-11 at 02 24 56" src="https://user-images.githubusercontent.com/7991920/148854453-7660abc9-5e79-4f5b-b8fd-1264c82d359c.png">

The error I'm getting in both cases is: _The server returned an invalid or incomplete response._

**Expected behavior**
I expect to receive/upload a file.

**Setup (please complete the following information):**
 - OS: macOS Monterey (12.1)
 - Version of soto: 4.7.2
 - Authentication mechanism: access key + secret key

**Comment by adam-fowler** [comment]
A Couple of questions:
Have you tried your code on AWS S3?
Is it possible for you to try this with the latest v5 of Soto

**Comment by Jauzee** [comment]
I don't have AWS to try. But just tried with 5.0.0 and it works fine.

One thing to note here. To use soto 5.0.0 on macOS you must update swift-tools-version to 5.5 and set macOS(.v12)
I forked the repo and changed it for myself: https://github.com/Jauzee/soto/commit/87e3effaadf7c7b0e33b10ac452c42ba163430f9

**Comment by Jauzee** [comment]
I think we can close this issue. I will just use 5.0.
