### ISSUE TITLE
Tryint to call GetAccountSendingEnabled on SES and getting UnknownOperationException from AWS

### ISSUE THREAD

**Issue by lordbarrison** [soto-project/soto#580]
**Describe the bug**
I'm just trying to make some simple calls to kick the tires on Soto. Here's a snippet of code

```swift
public func getSesSendingEnabled(account: String) async throws -> Bool {
    let ses = SES(client: self.clients[getAwsAccount(environment: account)]!, region: .uswest2)
    let response = try await ses.getAccountSendingEnabled()
    return response.enabled ?? false
  }
```
The `self.clients` is just a stash of pre-configured AWSClients and I've tested with S3 and I'm able to retrieve buckets successfully, so it feels like a problem with SES.

This response I get is this:

```
Unhandled error, code: notFound, body: <UnknownOperationException/>
```

I thought it might have needed an endpoint, so I tried the endpoint from here without luck: https://docs.aws.amazon.com/general/latest/gr/ses.html

**To Reproduce**
Code above covers it.

**Expected behavior**
I expect the call to work and return either true or false depending on the state of my account's SES.

**Setup (please complete the following information):**
 - OS: macOS 12.2.1
 - Version of soto: 5.12.1
 - Authentication mechanism: static IAM access/secret keys (not checked in, of course!)

**Additional context**
Like I said, at least the call to fetch S3 buckets worked, so I know the client is good, creds are good (IAM permissions are wide open for now)

Thanks!
Barry

**Comment by adam-fowler** [comment]
I believe this is being caused by an error in the creation of query style requests which have no body (they still need a body containing the service name and version). Most services don't care but obviously SES does. I will have a look at fixing this today.

**Comment by adam-fowler** [comment]
Can you update your packages so you have Soto-core 5.9.3 and test again

**Comment by barryw** [comment]
@adam-fowler I'm pulling in `https://github.com/soto-project/soto.git`. Has that been updated, or just soto-core?

**Comment by adam-fowler** [comment]
I've verified this as working so am going to close. If you are still having issues please re-open

**Comment by barryw** [comment]
@adam-fowler Thank you for fixing this so quickly!
