### ISSUE TITLE
S3 PutObject fails if request has double whitespaces in content disposition

### ISSUE THREAD

**Issue by t-ae** [soto-project/soto#584]
**Describe the bug**

Calling `S3.putObject` with `contentDisposition` that specifies filename which contains double white spaces always fails.

**To Reproduce**

```swift
let client: S3

let fileName = "double  whitespace.txt"
let contentDisposition = "inline; filename=\"\(fileName)\""

let resp = try! client.putObject(
    S3.PutObjectRequest(
        body: AWSPayload.data(Data()),
        bucket: bucketName,
        contentDisposition: contentDisposition,
        key: "test/foo.txt"
    )
).wait()
// Fatal error: 'try!' expression unexpectedly raised an error: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Setup (please complete the following information):**
 - OS: macOS / Ubuntu
 - Version of soto: 5.12.1
 - Authentication mechanism [hard-coded credentials, IAM Instance Profile on EC2, etc]

**Comment by adam-fowler** [comment]
Ok, not totally sure what is going on here. It looks like it is related to all header fields that include a double space.

**Comment by adam-fowler** [comment]
Found the issue. When building the canonical request for signing I needed to replace sequential spaces with a single space.
