### ISSUE TITLE
Using Cloudflare R2 prompts STREAMING-AWS4-HMAC-SHA256-PAYLOAD not implemented

### ISSUE THREAD

**Issue by gee1k** [soto-project/soto#643]
**Describe the bug**
Upload to Cloudflare R2 using the S3 API `PutObjectRequest`, prompts `STREAMING-AWS4-HMAC-SHA256-PAYLOAD not implemented`

**To Reproduce**

**Expected behavior**

**Setup (please complete the following information):**
 - OS: macos
 - Version of soto: 6.3.0
 - Authentication mechanism hard-coded credentials

**Comment by gee1k** [comment]
I found the following related content:

https://github.com/cloudflare/cloudflare-docs/issues/6133

https://github.com/cloudflare/cloudflare-docs/issues/6133

**Comment by gee1k** [comment]
Found the solution, just use `AWSPayload.data`, you can't use `AWSPayload.stream` because R2 doesn't support streaming uploads

**Comment by alexacz** [comment]
According to the [Cloudflare R2 documentation](https://developers.cloudflare.com/r2/examples/aws/aws-sdk-net/#upload-and-retrieve-objects): "_Cloudflare R2 does not currently support the SigV4 streaming implementation used by AWSSDK.S3._".
Below is an example of how to initialize the soto-S3 client with SigV4 streaming disabled.

```swift
let client = AWSClient(credentialProvider:
        .static(accessKeyId: "R2_KEY_ID",secretAccessKey: "R2_ACCESS_KEY"))
let s3 = S3(client: client,
            region: .other("R2_LOCATION"),
            endpoint: "R2_ENDPOINT",
            options: [.s3DisableChunkedUploads]) // Disable S3 signed chunked uploads
```
