### ISSUE TITLE
Add Cocoapods support

### ISSUE THREAD

**Issue by YoavGro** [soto-project/soto#645]
**Describe the solution you'd like**
Being able to add soto to my project with cocoapods

**Additional context**
We are working on a share lib for both iOS and MacOS, and to be able to use this in both platforms we need to run Soto from Cocoapods

**Comment by adam-fowler** [comment]
There aren't currently any plans to add cocoapods support. Why do you need support? SwiftPM works for both platforms.

**Comment by YoavGro** [comment]
Hi, 

We want to use this lib using our shared code library which is delivered to our apps using a pod, we are able to move our dependencies using the podspec file except for this framework

**Comment by 0xTim** [comment]
Given that Soto is about to move to using a Swift Package Plug-in to generate the code for each service, I'd say it's unlikely cocoapods will ever be supported

**Comment by YoavGro** [comment]
Ok got it, thanks 
We'll find some sort of workaround to using Cocoapods

**Comment by adam-fowler** [comment]
The full source version of Soto will be available for still some time, but we are dependent on swift-server/async-http-client which does not have a cocoa-pod so it still won't be possible.
