### ISSUE TITLE
Multiplepart upload pause, resume and stop state manage  

### ISSUE THREAD

**Issue by miteshpopenxcell** [soto-project/soto#654]

**Comment by adam-fowler** [comment]
You can throw an error from the progress callback to pause a multipart upload. If you catch the error thrown by the multipart system it will include this error plus a structure that will allow you to resume the upload with `S3.ResumeMultipartUpload`.

**Comment by miteshpopenxcell** [comment]
Hello,

Thank you for your quick reply can you provide me with a detailed code?

**Comment by adam-fowler** [comment]
I'm not here to write your code, but you can find a more detailed answer here https://github.com/soto-project/soto/discussions/616

**Comment by miteshpopenxcell** [comment]
okay thanks
