### ISSUE TITLE
When I am trying to upload video using VPN 

### ISSUE THREAD

**Issue by miteshpopenxcell** [soto-project/soto#655]
Getting error : - "POSIXErrorCode(rawValue: 54): Connection reset by peer" 

Can you please help me?

**Comment by adam-fowler** [comment]
Do any operations work across a VPN eg GetObject?

Can you post some code that shows the problem, what version of Soto, Swift are you using and what platform are you running on?

**Comment by miteshpopenxcell** [comment]
Hello,

I am using VPN(US) Location and a request is a multipart upload. The Soto version is 6.0.0, and the swift version(4.2), the platform is iPhone.

[SOTO.pdf](https://github.com/soto-project/soto/files/10389961/SOTO.pdf)

**Comment by miteshpopenxcell** [comment]
Sorry, Yes 5.2,

I am using mobile data and Third-party VPN App(https://apps.apple.com/us/app/id1641457212). Having problems uploading videos.

**Comment by adam-fowler** [comment]
Ah I think I know what your issue is. Soto does not use `URLSession` so does not respect iPhone proxy settings. You can possibly get around this by setting up the proxy configuration in `HTTPClient` used by `AWSClient`.

```swift
import AsyncHTTPClient

let httpClient = HTTPClient(
    eventLoopGroupProvider: .createNew, 
    configuration: .init(proxy: .server(host: *, port: *, authorization: *)
)
let awsClient = AWSClient(..., httpClientProvider: .shard(httpClient)
```
