### ISSUE TITLE
Textract.ValueType fails to parse

### ISSUE THREAD

**Issue by klemenkosir** [soto-project/soto#656]
**Describe the bug**
Making a Textract AnalyzeID request returns a response that fails to parse. The failure is specifically the `Textract.ValueType`.

```
Cannot initialize ValueType from invalid String value Date for key IdentityDocuments.Index 0.IdentityDocumentFields.Index 9.ValueDetection.NormalizedValue.ValueType
```
It's expecting to decode `ValueType: "DATE"` but it gets `ValueType: "Date"`.
I know the documentation clearly states "DATE" on multiple occasions, but as you can see on the [Amazon Blog](https://aws.amazon.com/blogs/machine-learning/announcing-support-for-extracting-data-from-identity-documents-using-amazon-textract/) or my own console printout
```
{
    Type =                     {
        Text = "DATE_OF_ISSUE";
    };
    ValueDetection =                     {
        Confidence = "97.49214172363281";
        NormalizedValue =                         {
            Value = "2016-11-30T00:00:00";
            ValueType = Date;
        };
        Text = "30/11/2016";
    };
}
```
this is clearly not the case.

What I suggest is making the `ValueType` **case-insensitive**. This should cover possible future changes on AWS side to 'DATE', if they ever change it.

I will gladly create a PR with a fix for this, I just wanted to make sure I'm not missing anything here.

**To Reproduce**
1. Create a Textract AnalyzeID request for an image of a passport
2. Execute the request using `textract.analyzeID(request)`
3. Fail to parse the response

**Expected behavior**
I expected to get a response that would parse just fine.

**Setup (please complete the following information):**
 - OS: MacOS Ventura 13.1 running Xcode 14.2
 - Version of soto: 6.4.0
 - Authentication mechanism: static credentials

**Comment by adam-fowler** [comment]
The services code in Soto is generated by the [SotoCodeGenerator](https://github.com/soto-project/soto-CodeGenerator) project. You can't just edit the service files directly you need to make the fix in the code generator and then your fix is applied across all the service files.

I'm interested in how you were thinking of making the enum decoding case-insensitive though.

Also out of interest have you found if any of the other Textract enums are incorrect? They are all uppercase in the model file but if `Date` is wrong there is a chance other enums are also wrong.

**Comment by klemenkosir** [comment]
Thanks @adam-fowler. I'll look at the SotoCodeGenerator project.

Regarding the parsing, i would just implement a custom ` init(from decoder: Decoder) throws` where i would first get the String for key, forced it to be uppercased and then call `init(rawValue:)` on the enum.

I checked all the other types that I could find in the response and they were all uppercased, this `ValueType: Date` is an anomaly. 🙈

**Comment by klemenkosir** [comment]
Looks like the json model definition is wrong. https://github.com/soto-project/soto/blob/main/models/textract.json

**Comment by adam-fowler** [comment]
I'm not overly keen on adding custom decoders for every enum. That is a huge amount of code. 

There is a patch process where we patch the model files after they are loaded by the code generator. I have used this to change the case of enums before. You'll find the code [here](https://github.com/soto-project/soto-codegenerator/blob/main/Sources/SotoCodeGeneratorLib/Model+Patch.swift).

Another option is to add a custom trait which flags an enum as case insensitive and then for enums with this trait we generate the custom decoder. This limits the additional code to only the enums that we have recognised as inconsistent. You'd have to go pretty deep into the code generator to do that though.

**Comment by adam-fowler** [comment]
> Looks like the json model definition is wrong

In theory it isn't. AWS wrote a get out clause into their Smithy spec that said enums are case insensitive. Very few are though. It is just the occasional one that exists. I think I have come across maybe three in the four years I've been working on Soto.

**Comment by klemenkosir** [comment]
Ah okay so its basically the Swift SDK's fault for not having enums case-insensitive, since they are almost always uppercased.

I'll take a look at the patching you've linked.

**Comment by klemenkosir** [comment]
```
 "Textract": [
            "com.amazonaws.textract#ValueType$Date": EditTraitPatch { _ in EnumValueTrait(value: .string("Date")) },
            }
```
would adding something like this do the trick?

**Comment by adam-fowler** [comment]
That'd work.
I might do the custom trait at a later date. Although the only other trait I see which has a different case is `com.amazonaws.ec2#PlatformValues$Windows`

**Comment by klemenkosir** [comment]
PRd https://github.com/soto-project/soto-codegenerator/pull/69

**Comment by adam-fowler** [comment]
Rebuilt Soto source and did a new release so you fix in SotoCodeGenerator will have propagated through to Soto
