### ISSUE TITLE
I am getting below error while uploading more then 8 images on same time.

### ISSUE THREAD

**Issue by miteshpopenxcell** [soto-project/soto#674]
▿ HTTPClientError.getConnectionFromPoolTimeout
  - code: AsyncHTTPClient.HTTPClientError.(unknown context at $106438ab8).Code.getConnectionFromPoolTimeout

**Comment by adam-fowler** [comment]
This is an error returned by https://github.com/swift-server/async-http-client. It is most likely because you are running too many concurrent requests (although the error message is not very helpful).
