### ISSUE TITLE
Decoding failure

### ISSUE THREAD

**Issue by Buratti** [soto-project/soto#720]
**Describe the bug**
`Lambda.UpdateFunctionConfiguration` fails when it comes to decode the response. The function configuration is updated correctly.

```
dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "LastUpdateStatusReasonCode", intValue: nil)], debugDescription: "Cannot initialize LastUpdateStatusReasonCode from invalid String value Creating", underlyingError: nil))
```

**To Reproduce**
```swift
let httpClient = HTTPClient(eventLoopGroupProvider: .singleton)
let awsClient = AWSClient(httpClientProvider: .createNew)

defer {
    try? awsClient.syncShutdown()
    try? httpClient.syncShutdown()
}

let lambda = Lambda(client: awsClient)
let request = Lambda.UpdateFunctionConfigurationRequest(functionName: "")
_ = try await lambda.updateFunctionConfiguration(request)
```
**Expected behavior**
Should not fail

**Setup (please complete the following information):**
 - Version of soto: 6.8.0
 - Authentication mechanism: profile

**Additional context**
Tested in eu-central-1, should not be relevant though.

**Comment by 0xTim** [comment]
@Buratti are you able to breakpoint inside the HTTPClient call and get the JSON body returned? Because `Creating` should not be being returned as the reason code - https://docs.aws.amazon.com/lambda/latest/api/API_UpdateFunctionConfiguration.html#lambda-UpdateFunctionConfiguration-response-LastUpdateStatusReasonCode

**Comment by Buratti** [comment]
Sure! I'll need an hour though, I'm OOO right now. 
What I can tell you right now is that the I have tried the same invocation using aws-cli earlier, and it also returned `Creating`.
I'll paste the response received inside the HTTPClient in a new comment later!

**Comment by adam-fowler** [comment]
@Buratti would you be able to try this with the 7.0.0-rc version

**Comment by Buratti** [comment]
Breakpointing [here](https://github.com/soto-project/soto-core/blob/3ed66ec536bc372360d7e3ec39a5e8b1870747ea/Sources/SotoCore/AWSClient%2Basync.swift#L214) the response does indeed return a `"Creating"` string.

This looks like a bug on AWS side, I couldn't find any reference of `Creating` either and `GetFunctionConfiguration` does not even return it. `Creating` also looks like an unexpected case for a function that has been "created" and updated for over two years.

**Comment by adam-fowler** [comment]
It is a pain when the model files amazon provide are not up to date with the actual reality. I have add a patch to code generator and have run it on the models. You can test the `aws-update-models` branch, but that'll require you to upgrade to 7.0 code base. As long as you are only using Swift concurrency that shouldn't be too hard.

I'm hoping to do v7 release in the very near future

**Comment by adam-fowler** [comment]
> Looks like they've just updated them (it's in #717)

That's my patch

**Comment by 0xTim** [comment]
Oh lol I misread the PR 😅

**Comment by Buratti** [comment]
IMHO I would argue that this is a bug, not a "synchronization" problem with their models. Otherwise I couldn't understand why the difference behavior between `GetFunctionConfiguration` and `UpdateFunctionConfiguration`.
I've open a case on AWS Support and update this issue with their answer.

This isn't a big issue for us right now, it's a very simple helper script and I can work around it ignoring the DecodingError, not a big deal.

I will try the patch, migrating to soto 7 was very high on my priority list anyway (thanks for adding tracing support, loved seeing it).

**Comment by adam-fowler** [comment]
> IMHO I would argue that this is a bug, not a "synchronization" problem with their models.

You are probably correct, but AWS aren't always fast to move so I tend to patch models until they are fixed.

**Comment by adam-fowler** [comment]
This should be resolved in v7
