### ISSUE TITLE
Swift 6 warnings

### ISSUE THREAD

**Issue by MahdiBM** [soto-project/soto#730]
**Describe the bug**
When building on `swift:6.0-noble` image, I get these warnings:
```
warning: 'soto': found 774 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/__w/my-app/my-app/.build/checkouts/soto/Sources/Soto/Services/RDSData/RDSData_api.swift
/__w/my-app/my-app/.build/checkouts/soto/Sources/Soto/Extensions/CognitoIdentity/CognitoIdentity+CredentialProvider.swift
/__w/my-app/my-app/.build/checkouts/soto/Sources/Soto/Services/Kinesis/Kinesis_shapes.swift
/__w/my-app/my-app/.build/checkouts/soto/Sources/Soto/Services/ElasticsearchService/ElasticsearchService_api.swift
```

**To Reproduce**
Build on `swift:6.0-noble`

**Expected behavior**
No warnings

**Setup (please complete the following information):**
 - OS: Linux
 - Version of soto: latest

**Additional context**

**Comment by adam-fowler** [comment]
This is not something specific to Swift 6. It's been around for years. It's a bug in SwiftPM that seems to be at the bottom of the pile. 

Basically SwiftPM doesn't like the structure of Soto where a library can be spread across two folders and have other libraries folder structure interleaved with it. I specifically say in the manifest only look in these folders, but it still complains about files outside of them.

**Comment by MahdiBM** [comment]
Hmm perhaps Swift 6 is emitting the warning more prominently then.
I can believe that it was already there even before Swift 6, and I just didn't notice it too much.

**Comment by adam-fowler** [comment]
It looks like this wasn't being reported for users of soto in v5.10 and earlier. It only appeared for developers of the package. This has changed in v6. I have mentioned this in the bug and hopefully we'll see some resolution. If not I'll be forced into merging #732 and creating another major release

**Comment by MahdiBM** [comment]
This doesn't seem to stop there, and I think it's a general issue with warnings propagation of dependency Package.swifts.
I also see a bunch of these from other dependencies.
```
'swift-clocks': /.build/checkouts/swift-clocks/Package@swift-6.0.swift:5:15: warning: 'init(name:defaultLocalization:platforms:pkgConfig:providers:products:dependencies:targets:swiftLanguageVersions:cLanguageStandard:cxxLanguageStandard:)' is deprecated: replaced by 'init(name:defaultLocalization:platforms:pkgConfig:providers:products:dependencies:targets:swiftLanguageModes:cLanguageStandard:cxxLanguageStandard:)'
 3 | import PackageDescription
```
