### ISSUE TITLE
Broken "Using Soto on AWS Lambda" link in the readme

### ISSUE THREAD

**Issue by natanrolnik** [soto-project/soto#736]
I was trying to understand if Soto has any special behavior when running in a Lambda - how to configure it, if needed at all.

I found in the Readme, in the Documentation section, a sub-section named User Guides. One of the links there is **Using Soto on AWS Lambda**. The link there is https://soto.codes/user-guides/using-soto-on-aws-lambda.html, which leads to a 404. In the [Soto.codes](https://soto.codes/) menu, I found all other items, except for the Lambda one.

Is it missing from the website?

**Comment by adam-fowler** [comment]
I removed it because the documentation was out of date. I need to update it. There isn't anything too complex about using Soto in a lambda. The main thing you have to do is manage its lifecycle. Call `shutdown()` on it, when the lambda is done.

**Comment by natanrolnik** [comment]
Thanks for replying!

But running in Lambda still requires to configure credentials for Soto in one of the described ways, or is there some sort of magic that makes it work out of the box when running in a Lambda environment? Besides managing the lifecycle as you mentioned.

**Comment by adam-fowler** [comment]
Yeah the original post did have something about that. It is basically use the environment variables supplied to the lambda which are setup to the use the lambda execution role. The default credential provider checks the environment variables first if I remember right so you only need to setup the execution role.

**Comment by khinkson** [comment]
> I removed it because the documentation was out of date. I need to update it. There isn't anything too complex about using Soto in a lambda. The main thing you have to do is manage its lifecycle. Call `shutdown()` on it, when the lambda is done.

How should the shutdown() be called? I remember seeing in the example a while back and then the examples changed to not having shutdown called before it was removed.

**Comment by adam-fowler** [comment]
Fixed.
I've done some minor fixups for this.  I should be up to date for the current state of AWS Lambda runtime but the runtime is currently being re-worked to be more swift concurrency friendly. Once an alpha of that is released I'll update this as the event loop to swift concurrency stuff is a little clunky

**Comment by khinkson** [comment]
Out of curiosity, what's the danger in not calling shutdown? 

I'm running soto 7.1.0 with the 1.0.0-alpha.3 runtime. I'm using LambdaHandler with an init and a handle function and nothing else. I've been looking for references to shutdown that might be called on LambdaHandler but I'm not seeing any.

**Comment by adam-fowler** [comment]
> Out of curiosity, what's the danger in not calling shutdown?
> 
> I'm running soto 7.1.0 with the 1.0.0-alpha.3 runtime. I'm using LambdaHandler with an init and a handle function and nothing else. I've been looking for references to shutdown that might be called on LambdaHandler but I'm not seeing any.

In this situation it probably wouldn't be the end of the world if you didn't shutdown a global variable AWSClient.
