### ISSUE TITLE
Cannot find `NSString` in scope: soto 7.1.0 / xcode 16

### ISSUE THREAD

**Issue by mmaetzler** [soto-project/soto#741]
**Describe the bug**
When adding soto 7.1.0 to an empty iOS Swift project, the build fails with:
`Cannot find 'NSString' in scope`

```
/Users/someuser/Library/Developer/Xcode/DerivedData/test-gwceghdpjkuyutdbcgkieedjljhs/SourcePackages/checkouts/soto-core/Sources/SotoCore/Credential/ConfigFileLoader.swift:302:16: error: cannot find 'NSString' in scope
        return NSString(string: filePath).expandingTildeInPath
               ^~~~~~~~
```
               

**To Reproduce**
1. Create new iOS/Swift app project in Xcode Version 16.0 (16A242d)
2. Add soto as an SPM dependency, with exact version set to `7.1.0`
3. Add `SotoSTS` and `SotoS3` to the build target
4. build
5. observe error

**Expected behavior**
Adding Soto to an otherwise empty project should build.

**Setup (please complete the following information):**
 - OS: `macOS Sonoma 14.6.1 (23G93)`
 - Version of soto: `7.1.0`
 - Authentication mechanism [hard-coded credentials, IAM Instance Profile on EC2, etc]: `n/a`
 - Xcode: `Version 16.0 (16A242d)`
 - iOS deployment target: `iOS18`

**Screenshots**
<img width="974" alt="image" src="https://github.com/user-attachments/assets/e705f16f-2f31-4123-8b0e-414f3e0d19d8">

<img width="1478" alt="image" src="https://github.com/user-attachments/assets/c9ab7020-858f-4c88-b338-0c54ec1f775d">

<img width="1079" alt="image" src="https://github.com/user-attachments/assets/44218e3d-8806-45c8-84ad-7538cd1ff9e6">

**Comment by adam-fowler** [comment]
soto-core 7.2.0 should fix this

**Comment by mmaetzler** [comment]
Thanks for the fast reply! 
Would you mind pushing a new soto SPM release that points to soto-core 7.2.0? The 7.1.0 release as-is is non-functional, so the ticket is still open as 7.1.0 cannot be used.

Background: We have updated our code from using the 6.x to the 7.x release but are stuck because soto does not build anymore.

**Comment by adam-fowler** [comment]
If you run update dependencies you should get 7.2.0 Soto-core.
As the dependency is set to `from: "7.1.0"` it will pick up the latest minor release which is 7.2.0.
